### ISSUE TITLE
TemplateEngine: render fails on multiple tags on the same line

### ISSUE THREAD

**Issue by yanis-viola-nxp** [socon-dev/socon#48]
working case:
{{ tag1 }}
{{ tag2 }}
{{ tag3 }}

issue with:
{{ tag1 }} {{ tag2 }}
{{ tag3 }}

-> render takes "tag1 }} {{ tag2" as tag instead of "tag1" and "tag2" separately

**Comment by StephaneCapponi** [comment]
Hello, Thanks Yanis for the feedback. Can you add an entry in the changelog folder like the following:
echo "Fix template rendering when multiple tags are passed on the same line" > changelog/48.bugfix.rst 

You can can commit that file with your pull request

**Comment by yanis-viola-nxp** [comment]
> Hello, Thanks Yanis for the feedback. Can you add an entry in the changelog folder like the following: echo "Fix template rendering when multiple tags are passed on the same line" > changelog/48.bugfix.rst
> 
> You can can commit that file with your pull request

Hello,
Sorry I missed the message, maybe for the next time ;-)
