### ISSUE TITLE
Create a built-in createcommand command

### ISSUE THREAD

**Issue by StephaneCapponi** [socon-dev/socon#6]
We should implement a **createcommand** command. This command would be based on TemplateCommand and will help the end user create easily a new command for their framework or plugins.

This command must be use inside a container, a plugin or inside a project. We could add a `--target` option to specify where it should be created. Also, it would be great to have another option `--type` that specify if it's a ProjectCommand or a BaseCommand.

This command must be a BaseCommand as it does not depend on a ProjectConfig.

The command must create the management/commands folder structure if it does not exist. We need to implement a way to detect if it's the case or not.

**Comment by JRbemt** [comment]
Hey, I like the project and could try to implement this in the coming days

**Comment by StephaneCapponi** [comment]
Hey @JRbemt, Awesome! that would be super helpful. All help is really appreciated.
As you might be the first contributor, do not hesitate if you see any flaw in the process!
